/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import service.SekolahService;

/**
 *
 * @author ACER NITRO
 */
public class DialogTambahSekolah extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(DialogTambahSekolah.class.getName());
    private final SekolahService sekolahService;

    public DialogTambahSekolah(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.sekolahService = new SekolahService();
        
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
        
        txtAlamatSekolah.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                      
        ));
        txtEmail.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtJabatan.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtKabupatenKota.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtKecamatan.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
         txtNPSN.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtNamaSekolah.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtNoHP.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
        txtPassword.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),   
            new EmptyBorder(5, 10, 5, 10)                       
        ));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        cbJenisSekolah = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tambahSekolahBtn = new javax.swing.JButton();
        txtKabupatenKota = new javax.swing.JTextField();
        txtAlamatSekolah = new javax.swing.JTextField();
        txtNamaSekolah = new javax.swing.JTextField();
        txtNPSN = new javax.swing.JTextField();
        txtKecamatan = new javax.swing.JTextField();
        txtNoHP = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbJenisSekolah.setBackground(new java.awt.Color(255, 255, 255));
        cbJenisSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbJenisSekolah.setForeground(new java.awt.Color(51, 51, 51));
        cbJenisSekolah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "SMK", "SLB" }));
        cbJenisSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisSekolahActionPerformed(evt);
            }
        });
        jPanel8.add(cbJenisSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 310, 50));

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Data Akun Sekolah");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat Sekolah");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Sekolah");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("NPSN");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Jenis Sekolah");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, 20));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Password");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, 20));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kabupaten / Kota");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, 20));

        tambahSekolahBtn.setBackground(new java.awt.Color(30, 136, 229));
        tambahSekolahBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tambahSekolahBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahSekolahBtn.setText("Tambah Sekolah");
        tambahSekolahBtn.setToolTipText("");
        tambahSekolahBtn.setBorder(null);
        tambahSekolahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSekolahBtnActionPerformed(evt);
            }
        });
        jPanel8.add(tambahSekolahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 130, 34));

        txtKabupatenKota.setBackground(new java.awt.Color(255, 255, 255));
        txtKabupatenKota.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtKabupatenKota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtKabupatenKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKabupatenKotaActionPerformed(evt);
            }
        });
        jPanel8.add(txtKabupatenKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 370, 50));

        txtAlamatSekolah.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtAlamatSekolah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtAlamatSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatSekolahActionPerformed(evt);
            }
        });
        jPanel8.add(txtAlamatSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 630, 50));

        txtNamaSekolah.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNamaSekolah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtNamaSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSekolahActionPerformed(evt);
            }
        });
        jPanel8.add(txtNamaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 630, 50));

        txtNPSN.setBackground(new java.awt.Color(255, 255, 255));
        txtNPSN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNPSN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtNPSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPSNActionPerformed(evt);
            }
        });
        jPanel8.add(txtNPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, 50));

        txtKecamatan.setBackground(new java.awt.Color(255, 255, 255));
        txtKecamatan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtKecamatan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtKecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKecamatanActionPerformed(evt);
            }
        });
        jPanel8.add(txtKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 50));

        txtNoHP.setBackground(new java.awt.Color(255, 255, 255));
        txtNoHP.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNoHP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtNoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHPActionPerformed(evt);
            }
        });
        jPanel8.add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 310, 50));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel8.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 310, 50));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Kecamatan");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("No HP");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 20));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel8.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 310, 50));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Email");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 20));

        txtJabatan.setBackground(new java.awt.Color(255, 255, 255));
        txtJabatan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtJabatan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanActionPerformed(evt);
            }
        });
        jPanel8.add(txtJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 310, 50));

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Jabatan");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, 20));

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Tambah Sekolah Baru");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahSekolahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSekolahBtnActionPerformed
        tambahSekolahBaru();
    }//GEN-LAST:event_tambahSekolahBtnActionPerformed

    private void txtKabupatenKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKabupatenKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKabupatenKotaActionPerformed

    private void cbJenisSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisSekolahActionPerformed

    private void txtAlamatSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatSekolahActionPerformed

    private void txtNamaSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSekolahActionPerformed

    private void txtNPSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPSNActionPerformed

    private void txtKecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKecamatanActionPerformed

    private void txtNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanActionPerformed
    
    private void tambahSekolahBaru() {
        try {
            String namaSekolah = txtNamaSekolah.getText().trim();
            String npsn         = txtNPSN.getText().trim();
            String alamat       = txtAlamatSekolah.getText().trim();
            String kecamatan    = txtKecamatan.getText().trim();
            String kabupaten    = txtKabupatenKota.getText().trim();
            String kategori     = String.valueOf(cbJenisSekolah.getSelectedItem());

            String email        = txtEmail.getText().trim();
            String password     = new String(txtPassword.getPassword());
            String noHp         = txtNoHP.getText().trim();
            String jabatan      = txtJabatan.getText().trim();

            if (namaSekolah.isEmpty() || npsn.isEmpty() || alamat.isEmpty() ||
                kecamatan.isEmpty() || kabupaten.isEmpty() ||
                email.isEmpty() || password.isEmpty() || noHp.isEmpty() || jabatan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            SekolahService.OperationResult result = sekolahService.tambahSekolahDenganAkun(
                    namaSekolah, kategori, alamat, kecamatan, kabupaten, npsn,
                    "-",                 // kebutuhan default
                    email, password, noHp, jabatan
            );

            if (result.isSuccess()) {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogTambahSekolah dialog = new DialogTambahSekolah(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJenisSekolah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton tambahSekolahBtn;
    private javax.swing.JTextField txtAlamatSekolah;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtKabupatenKota;
    private javax.swing.JTextField txtKecamatan;
    private javax.swing.JTextField txtNPSN;
    private javax.swing.JTextField txtNamaSekolah;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

}
