package view.dialog;

import model.Donatur;
import dao.DonaturDAO;
import dao.DonaturDAOImpl;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 * DialogManajemenDonatur
 * Dialog untuk view profil donatur lengkap
 * Terintegrasi dengan DAO layer untuk data access
 * 
 * @author EduShare Team
 */
public class DialogManajemenDonatur extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(DialogManajemenDonatur.class.getName());
    
    // DAO Layer
    private final DonaturDAO donaturDAO;
    
    // Data Model
    private Donatur donaturCurrent;
    private Integer idDonatur;

    /**
     * Constructor untuk view existing donatur
     */
    public DialogManajemenDonatur(java.awt.Frame parent, boolean modal, Integer idDonatur) {
        super(parent, modal);
        this.donaturDAO = new DonaturDAOImpl();
        this.idDonatur = idDonatur;
        
        initComponents();
        setupDialog();
        loadDonaturData();
    }
    
    /**
     * Constructor default (untuk compatibility dengan form editor)
     */
    public DialogManajemenDonatur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.donaturDAO = new DonaturDAOImpl();
        
        initComponents();
        setupDialog();
    }
    
    /**
     * Setup dialog properties
     */
    private void setupDialog() {
        setTitle("Profil Donatur");
        setLocationRelativeTo(getParent());
        setResizable(false);
    }
    
    /**
     * Load data donatur dari database
     */
    private void loadDonaturData() {
        if (idDonatur == null) {
            JOptionPane.showMessageDialog(this,
                "ID Donatur tidak valid",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        
        try {
            Optional<Donatur> donaturOpt = donaturDAO.findById(idDonatur);
            
            if (donaturOpt.isPresent()) {
                this.donaturCurrent = donaturOpt.get();
                populateForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data donatur tidak ditemukan",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                dispose();
            }
            
        } catch (Exception e) {
            logger.severe("Error loading donatur data: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error loading data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
    
    /**
     * Populate form dengan data donatur
     */
    private void populateForm() {
        if (donaturCurrent == null) return;
        
        // Populate all fields from Donatur model
        namaSekolah2.setText(donaturCurrent.getNama());
        namaSekolah3.setText(donaturCurrent.getEmail());
        namaSekolah1.setText(donaturCurrent.getTotalDonasi() != null
            ? String.format("Rp %,.0f", donaturCurrent.getTotalDonasi())
            : "Rp 0");
        namaSekolah.setText(donaturCurrent.getAlamat() != null ? 
            donaturCurrent.getAlamat() : "-");
        
        // Update title dengan nama donatur
        jLabel14.setText("Profil Donatur - " + donaturCurrent.getNama());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        namaSekolah1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        namaSekolah = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        namaSekolah2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        namaSekolah3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Profil Donatur");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaSekolah1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaSekolah1.setForeground(new java.awt.Color(51, 51, 51));
        namaSekolah1.setText("Total Donasi");
        jPanel5.add(namaSekolah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaSekolah.setForeground(new java.awt.Color(51, 51, 51));
        namaSekolah.setText("Alamat Sekolah");
        jPanel4.add(namaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaSekolah2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaSekolah2.setForeground(new java.awt.Color(51, 51, 51));
        namaSekolah2.setText("Nama Donatur");
        jPanel6.add(namaSekolah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat Donatur");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Donatur");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaSekolah3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaSekolah3.setForeground(new java.awt.Color(51, 51, 51));
        namaSekolah3.setText("Email");
        jPanel7.add(namaSekolah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Total Donasi");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jButton10.setBackground(new java.awt.Color(30, 136, 229));
        jButton10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Oke");
        jButton10.setToolTipText("");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 130, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Close dialog
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * Cleanup resources saat dialog ditutup
     */
    @Override
    public void dispose() {
        if (donaturDAO instanceof DonaturDAOImpl) {
            ((DonaturDAOImpl) donaturDAO).close();
        }
        super.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogManajemenDonatur dialog = new DialogManajemenDonatur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel namaSekolah;
    private javax.swing.JLabel namaSekolah1;
    private javax.swing.JLabel namaSekolah2;
    private javax.swing.JLabel namaSekolah3;
    // End of variables declaration//GEN-END:variables
}
