/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import java.awt.Window;
import javax.swing.JOptionPane;
import model.Donasi;
import model.Sekolah;
import service.DonasiService;

/**
 *
 * @author ACER NITRO
 */
public class DialogDetailDonasi extends javax.swing.JDialog {
    
    private final Donasi donasi;
    private final DonasiService donasiService;

    public DialogDetailDonasi(Window parent, Donasi donasi) {
        super(parent, "Detail Donasi", ModalityType.APPLICATION_MODAL);
        this.donasi = donasi;
        this.donasiService = new DonasiService();
        initComponents();
        tampilkanDataDonasi();
        setTombolVisibilitas(donasi);
    }
    
    private void setTombolVisibilitas(Donasi donasi) {
        if (donasi.getStatusDonasi() == Donasi.StatusDonasi.berhasil ||
            donasi.getStatusDonasi() == Donasi.StatusDonasi.gagal ||
            donasi.getStatusDonasi() == Donasi.StatusDonasi.dibatalkan) {
            verifikasiBtn.setVisible(false);
            tolakBtn.setVisible(false);
        } else {
            verifikasiBtn.setVisible(true);
            tolakBtn.setVisible(true);
        }

    }

    /**
     * Menampilkan data donasi ke textfield
     */
    private void tampilkanDataDonasi() {
        try {
            if (donasi == null) {
                JOptionPane.showMessageDialog(this, "Data donasi tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Data Donatur
            namaDonaturField.setText(donasi.getDonatur().getNama());
            tanggalDonasiField.setText(donasi.getTanggalDonasi().toString());
            jumlahDiterimaField.setText("Rp " + String.format("%,.0f", donasi.getJumlahDonasi()));

            // Data Sekolah penerima
            Sekolah sekolah = donasi.getKebutuhan().getSekolah();
            if (sekolah != null) {
                namaPenerimaField.setText(sekolah.getNamaSekolah());
                alamatSekolahField.setText(sekolah.getAlamatSekolah());
                kecamatanField.setText(sekolah.getKecamatan());
                kabupatenField.setText(sekolah.getKabupaten());
            }

            // Status donasi
            statusDonasiField.setText(donasi.getStatusDonasi().name().toUpperCase());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data donasi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jumlahDiterimaField = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        alamatSekolahField = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        namaDonaturField = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        namaPenerimaField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        kecamatanField = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        kabupatenField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        statusDonasiField = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tolakBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        tanggalDonasiField = new javax.swing.JLabel();
        verifikasiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Detail Donasi");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlahDiterimaField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jumlahDiterimaField.setForeground(new java.awt.Color(51, 51, 51));
        jumlahDiterimaField.setText("Jumlah Diterima");
        jPanel5.add(jumlahDiterimaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alamatSekolahField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        alamatSekolahField.setForeground(new java.awt.Color(51, 51, 51));
        alamatSekolahField.setText("Alamat Sekolah");
        jPanel4.add(alamatSekolahField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaDonaturField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaDonaturField.setForeground(new java.awt.Color(51, 51, 51));
        namaDonaturField.setText("Nama Donatur");
        jPanel6.add(namaDonaturField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat  Sekolah Penerima");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Donatur");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaPenerimaField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaPenerimaField.setForeground(new java.awt.Color(51, 51, 51));
        namaPenerimaField.setText("Nama Penerima");
        jPanel7.add(namaPenerimaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nama Penerima");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Jumlah Diterima");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kecamatanField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        kecamatanField.setForeground(new java.awt.Color(51, 51, 51));
        kecamatanField.setText("Kecamatan");
        jPanel9.add(kecamatanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 50));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kecamatan");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kabupatenField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        kabupatenField.setForeground(new java.awt.Color(51, 51, 51));
        kabupatenField.setText("Kabupaten / Kota");
        jPanel10.add(kabupatenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 370, 50));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kabupaten / Kota");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusDonasiField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        statusDonasiField.setForeground(new java.awt.Color(51, 51, 51));
        statusDonasiField.setText("Status Donasi");
        jPanel11.add(statusDonasiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 630, 50));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Status Donasi");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        tolakBtn.setBackground(new java.awt.Color(255, 0, 0));
        tolakBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tolakBtn.setForeground(new java.awt.Color(255, 255, 255));
        tolakBtn.setText("Tolak");
        tolakBtn.setToolTipText("");
        tolakBtn.setBorder(null);
        tolakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolakBtnActionPerformed(evt);
            }
        });
        jPanel8.add(tolakBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, 34));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Tanggal Donasi");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggalDonasiField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tanggalDonasiField.setForeground(new java.awt.Color(51, 51, 51));
        tanggalDonasiField.setText("Tanggal Donasi");
        jPanel13.add(tanggalDonasiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 310, 50));

        verifikasiBtn.setBackground(new java.awt.Color(30, 136, 229));
        verifikasiBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        verifikasiBtn.setForeground(new java.awt.Color(255, 255, 255));
        verifikasiBtn.setText("Verifikasi");
        verifikasiBtn.setToolTipText("");
        verifikasiBtn.setBorder(null);
        verifikasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasiBtnActionPerformed(evt);
            }
        });
        jPanel8.add(verifikasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tolakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolakBtnActionPerformed
        // TODO add your handling code here:
        String alasan = JOptionPane.showInputDialog(this, "Masukkan alasan penolakan:");
        if (alasan == null || alasan.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alasan penolakan wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menolak donasi ini?",
                "Konfirmasi Penolakan",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            var result = donasiService.batalkanDonasi(donasi.getIdDonasi(), alasan);
            JOptionPane.showMessageDialog(this, result.getMessage());
            if (result.isSuccess()) {
                statusDonasiField.setText("GAGAL");
                dispose();
            }
        }
    }//GEN-LAST:event_tolakBtnActionPerformed

    private void verifikasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasiBtnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin memverifikasi donasi ini?",
                "Konfirmasi Verifikasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            var result = donasiService.konfirmasiDonasi(donasi.getIdDonasi());
            JOptionPane.showMessageDialog(this, result.getMessage());
            if (result.isSuccess()) {
                statusDonasiField.setText("BERHASIL");
                dispose();
            }
        }
    }//GEN-LAST:event_verifikasiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatSekolahField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jumlahDiterimaField;
    private javax.swing.JLabel kabupatenField;
    private javax.swing.JLabel kecamatanField;
    private javax.swing.JLabel namaDonaturField;
    private javax.swing.JLabel namaPenerimaField;
    private javax.swing.JLabel statusDonasiField;
    private javax.swing.JLabel tanggalDonasiField;
    private javax.swing.JButton tolakBtn;
    private javax.swing.JButton verifikasiBtn;
    // End of variables declaration//GEN-END:variables
}
