/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import java.awt.Window;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Donatur;
import model.Kebutuhan;
import model.Pengguna;
import model.Sekolah;
import service.DonasiService;

/**
 *
 * @author ACER NITRO
 */
public class DialogDetailSekolah extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetailSekolah.class.getName());
    private final Kebutuhan kebutuhan;
    private final Sekolah sekolah;
    private final Pengguna user;
    private Runnable onDonasiSelesai;
    

    /**
     * Creates new form DialogDetailSekolah
     */
    

    public DialogDetailSekolah(Window parent, Kebutuhan kebutuhan, Sekolah sekolah, Pengguna user) {
        super(parent);
        initComponents();
        this.kebutuhan = kebutuhan;
        this.sekolah = sekolah;
        this.user = user;

        // Isi field sekolah
        if (sekolah != null) {
            txtNamaSekolah.setText(sekolah.getNamaSekolah());
            txtJenisSekolah.setText(sekolah.getKategori().toString());
            txtAlamatSekolah.setText(sekolah.getAlamatSekolah());
            txtKabupaten.setText(sekolah.getKabupaten());
            txtNPSN.setText(sekolah.getNpsn());
            txtKecamatan.setText(sekolah.getKecamatan());
            lblTarget.setText("Rp " + kebutuhan.getTargetDonasi());
            lblTerkumpul.setText("Rp " + kebutuhan.getTotalTerkumpul());
        }

        if (kebutuhan != null) {
            txtKebutuhan.setText(kebutuhan.getDeskripsi());
        }
    }
    
    public void setOnDonasiSelesai(Runnable onDonasiSelesai) {
        this.onDonasiSelesai = onDonasiSelesai;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        donasiBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtJenisSekolah = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtAlamatSekolah = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtNamaSekolah = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtNPSN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtKecamatan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtKabupaten = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtKebutuhan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblTerkumpul = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbltarget1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblTarget = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lbltarget3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Detail Sekolah");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        donasiBtn.setBackground(new java.awt.Color(30, 136, 229));
        donasiBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        donasiBtn.setForeground(new java.awt.Color(255, 255, 255));
        donasiBtn.setText("Donasi");
        donasiBtn.setToolTipText("");
        donasiBtn.setBorder(null);
        donasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donasiBtnActionPerformed(evt);
            }
        });
        jPanel8.add(donasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 130, 34));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJenisSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtJenisSekolah.setForeground(new java.awt.Color(51, 51, 51));
        txtJenisSekolah.setText("Jenis Sekolah");
        jPanel5.add(txtJenisSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAlamatSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtAlamatSekolah.setForeground(new java.awt.Color(51, 51, 51));
        txtAlamatSekolah.setText("Alamat Sekolah");
        jPanel4.add(txtAlamatSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNamaSekolah.setForeground(new java.awt.Color(51, 51, 51));
        txtNamaSekolah.setText("Nama Sekolah");
        jPanel6.add(txtNamaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat Sekolah");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Sekolah");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNPSN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNPSN.setForeground(new java.awt.Color(51, 51, 51));
        txtNPSN.setText("NPSN");
        jPanel7.add(txtNPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("NPSN");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Jenis Sekolah");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKecamatan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtKecamatan.setForeground(new java.awt.Color(51, 51, 51));
        txtKecamatan.setText("Kecamatan");
        jPanel9.add(txtKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 50));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kecamatan");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKabupaten.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtKabupaten.setForeground(new java.awt.Color(51, 51, 51));
        txtKabupaten.setText("Kabupaten / Kota");
        jPanel10.add(txtKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 370, 50));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kabupaten / Kota");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKebutuhan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtKebutuhan.setForeground(new java.awt.Color(51, 51, 51));
        txtKebutuhan.setText("Deskripsi Kebutuhan");
        jPanel11.add(txtKebutuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 630, 50));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Total Dana Terkumpul");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, 20));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTerkumpul.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTerkumpul.setForeground(new java.awt.Color(51, 51, 51));
        lblTerkumpul.setText("Total Terkumpul");
        jPanel12.add(lblTerkumpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltarget1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lbltarget1.setForeground(new java.awt.Color(51, 51, 51));
        lbltarget1.setText("Target");
        jPanel13.add(lbltarget1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 50));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 330, 50));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Deskripsi Kebutuhan");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarget.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTarget.setForeground(new java.awt.Color(51, 51, 51));
        lblTarget.setText("Target");
        jPanel14.add(lblTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltarget3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lbltarget3.setForeground(new java.awt.Color(51, 51, 51));
        lbltarget3.setText("Target");
        jPanel15.add(lbltarget3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 50));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 50));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Total Dana Diperlukan");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donasiBtnActionPerformed
        // TODO add your handling code here:
         // Pastikan kebutuhan valid
        if (kebutuhan == null) {
            JOptionPane.showMessageDialog(this, "Data kebutuhan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cek user login apakah Donatur
        if (!(user instanceof Donatur)) {
            JOptionPane.showMessageDialog(this, "Hanya Donatur yang bisa melakukan donasi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Donatur donatur = (Donatur) user;

        // Input jumlah donasi
        String inputJumlah = JOptionPane.showInputDialog(this, "Masukkan jumlah donasi (minimal Rp 10.000):", "Input Donasi", JOptionPane.PLAIN_MESSAGE);
        if (inputJumlah == null || inputJumlah.trim().isEmpty()) return;

        BigDecimal jumlahDonasi;
        try {
            // Hilangkan titik, koma, atau simbol rupiah jika ada
            String clean = inputJumlah.replaceAll("[^\\d]", "");
            jumlahDonasi = new BigDecimal(clean);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nominal donasi tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Pilih metode pembayaran
        String[] metodeOptions = {"TRANSFER", "CASH", "QRIS", "LAINNYA"};
        String metode = (String) JOptionPane.showInputDialog(
                this,
                "Pilih metode pembayaran:",
                "Metode Pembayaran",
                JOptionPane.QUESTION_MESSAGE,
                null,
                metodeOptions,
                metodeOptions[0]
        );

        if (metode == null) return;

        // Jalankan proses donasi
        DonasiService donasiService = new DonasiService();
        try {
            DonasiService.DonasiResult result = donasiService.buatDonasi(
                    donatur.getIdPengguna(),
                    kebutuhan.getIdKebutuhan(),
                    jumlahDonasi,
                    metode.toLowerCase().trim()
            );

            if (result.isSuccess()) {
                    JOptionPane.showMessageDialog(this, result.getMessage(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    lblTerkumpul.setText("Rp " + donasiService.getTotalDonasiKebutuhan(kebutuhan.getIdKebutuhan()));

                    // ✅ Jalankan callback kalau ada
                    if (onDonasiSelesai != null) {
                        onDonasiSelesai.run();
                    }

                    this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            donasiService.close();
        }
    }//GEN-LAST:event_donasiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donasiBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JLabel lblTerkumpul;
    private javax.swing.JLabel lbltarget1;
    private javax.swing.JLabel lbltarget3;
    private javax.swing.JLabel txtAlamatSekolah;
    private javax.swing.JLabel txtJenisSekolah;
    private javax.swing.JLabel txtKabupaten;
    private javax.swing.JLabel txtKebutuhan;
    private javax.swing.JLabel txtKecamatan;
    private javax.swing.JLabel txtNPSN;
    private javax.swing.JLabel txtNamaSekolah;
    // End of variables declaration//GEN-END:variables
}
