/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import dao.KebutuhanDAO;
import dao.KebutuhanDAOImpl;
import java.awt.Desktop;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import model.Dokumen;
import model.Kebutuhan;
import service.DokumenService;


/**
 *
 * @author ACER NITRO
 */
public class DialogDetailKebutuhan extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetailKebutuhan.class.getName());
    private final KebutuhanDAO kebutuhanDAO;
    private final Kebutuhan kebutuhan;
    private final DokumenService dokumenService;
    private final Integer idSekolah;



    public DialogDetailKebutuhan(java.awt.Frame parent, boolean modal, Kebutuhan kebutuhan) {
        super(parent, modal);
        this.kebutuhanDAO = new KebutuhanDAOImpl();
        this.kebutuhan = kebutuhan;
        this.dokumenService = new DokumenService();
        this.idSekolah = kebutuhan.getSekolah() != null ? kebutuhan.getSekolah().getIdSekolah() : null;

        initComponents();
        setupDialog();
        tampilkanData();
        cekStatus();
    }

    private void setupDialog() {
        setTitle("Detail Kebutuhan Sekolah");
        setResizable(false);
        setLocationRelativeTo(getParent());
    }

    private void tampilkanData() {
        try {
            if (kebutuhan == null || kebutuhan.getSekolah() == null) {
                JOptionPane.showMessageDialog(this, "Data kebutuhan atau sekolah tidak tersedia!");
                return;
            }

            // Ambil daftar dokumen milik sekolah
            List<Dokumen> dokumenList = dokumenService.getDokumenBySekolah(idSekolah);
            String namaFile = "-";
            String pathFile = null;

            if (dokumenList != null && !dokumenList.isEmpty()) {
                Dokumen dokumen = dokumenList.get(0); // ambil dokumen pertama
                namaFile = getSafeText(dokumen.getNamaFile());
                pathFile = dokumen.getPathFile();
            }

            // Set semua label data
            labelNamaSekolah.setText(getSafeText(kebutuhan.getSekolah().getNamaSekolah()));
            labelNamaAlat.setText(getSafeText(kebutuhan.getNamaAlat()));
            labelJumlah.setText(String.format("%d unit", kebutuhan.getJumlah() != null ? kebutuhan.getJumlah() : 0));
            labelPrioritas.setText(kebutuhan.getPrioritas() != null ? kebutuhan.getPrioritas().name() : "-");
            labelStatus.setText("Status: " + (kebutuhan.getStatus() != null ? kebutuhan.getStatus().name() : "-"));
            labelDeskripsiKebutuhan.setText(getSafeText(kebutuhan.getDeskripsi()));
            labelAlamatSekolah.setText(getSafeText(kebutuhan.getSekolah().getAlamatSekolah()));
            labelJenisSekolah.setText(kebutuhan.getSekolah().getKategori() != null
                    ? kebutuhan.getSekolah().getKategori().toString()
                    : "-");
            labelNPSN.setText(getSafeText(kebutuhan.getSekolah().getNpsn()));
            labelKabupaten.setText(getSafeText(kebutuhan.getSekolah().getKabupaten()));
            labelKecamatan.setText(getSafeText(kebutuhan.getSekolah().getKecamatan()));
            // Set nama file dokumen
            labelNamaFile.setText(namaFile);
            labelNamaFile.putClientProperty("filePath", pathFile); // simpan path-nya ke properti label (buat dipakai nanti)

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Gagal menampilkan data kebutuhan: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    private String getSafeText(String value) {
        return value != null && !value.trim().isEmpty() ? value : "-";
    }
    
    private void cekStatus() {
        if (kebutuhan.getStatus() == Kebutuhan.Status.diverifikasi
                || kebutuhan.getStatus() == Kebutuhan.Status.ditolak
                || kebutuhan.getStatus() == Kebutuhan.Status.terpenuhi) {
            verifBtn.setVisible(false);
            tolakBtn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelJenisSekolah = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelAlamatSekolah = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelNamaSekolah = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelNPSN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelKecamatan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelKabupaten = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        labelNamaAlat = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        labelNamaFile = new javax.swing.JLabel();
        lihatDokumenBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        verifBtn = new javax.swing.JButton();
        tolakBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        labelDeskripsiKebutuhan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        labelJumlah = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        labelPrioritas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Detail Kebutuhan");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJenisSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelJenisSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelJenisSekolah.setText("Jenis Sekolah");
        jPanel5.add(labelJenisSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAlamatSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelAlamatSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelAlamatSekolah.setText("Alamat Sekolah");
        jPanel4.add(labelAlamatSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNamaSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNamaSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaSekolah.setText("Nama Sekolah");
        jPanel6.add(labelNamaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat Sekolah");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Sekolah");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNPSN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNPSN.setForeground(new java.awt.Color(51, 51, 51));
        labelNPSN.setText("NPSN");
        jPanel7.add(labelNPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("NPSN");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Jenis Sekolah");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKecamatan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelKecamatan.setForeground(new java.awt.Color(51, 51, 51));
        labelKecamatan.setText("Kecamatan");
        jPanel9.add(labelKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 50));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kecamatan");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKabupaten.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelKabupaten.setForeground(new java.awt.Color(51, 51, 51));
        labelKabupaten.setText("Kabupaten / Kota");
        jPanel10.add(labelKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 370, 50));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kabupaten / Kota");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNamaAlat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNamaAlat.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaAlat.setText("Nama Alat");
        jPanel11.add(labelNamaAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 250, 50));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nama Alat");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 20));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNamaFile.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNamaFile.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaFile.setText("Nama File Pendukung");
        jPanel12.add(labelNamaFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        lihatDokumenBtn.setBackground(new java.awt.Color(30, 136, 229));
        lihatDokumenBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lihatDokumenBtn.setForeground(new java.awt.Color(255, 255, 255));
        lihatDokumenBtn.setText("Lihat Dokumen Pendukung");
        lihatDokumenBtn.setToolTipText("");
        lihatDokumenBtn.setBorder(null);
        lihatDokumenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDokumenBtnActionPerformed(evt);
            }
        });
        jPanel12.add(lihatDokumenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 190, 50));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 630, 50));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Dokumen Pendukung");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, 20));

        verifBtn.setBackground(new java.awt.Color(30, 136, 229));
        verifBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        verifBtn.setForeground(new java.awt.Color(255, 255, 255));
        verifBtn.setText("Verifikasi");
        verifBtn.setToolTipText("");
        verifBtn.setBorder(null);
        verifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifBtnActionPerformed(evt);
            }
        });
        jPanel8.add(verifBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 750, 130, 34));

        tolakBtn.setBackground(new java.awt.Color(255, 0, 0));
        tolakBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tolakBtn.setForeground(new java.awt.Color(255, 255, 255));
        tolakBtn.setText("Tolak");
        tolakBtn.setToolTipText("");
        tolakBtn.setBorder(null);
        tolakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolakBtnActionPerformed(evt);
            }
        });
        jPanel8.add(tolakBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 750, 130, 34));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDeskripsiKebutuhan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelDeskripsiKebutuhan.setForeground(new java.awt.Color(51, 51, 51));
        labelDeskripsiKebutuhan.setText("Deskripsi Kebutuhan");
        jPanel13.add(labelDeskripsiKebutuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 370, 130));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Deskripsi Kebutuhan");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 200, 20));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJumlah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(51, 51, 51));
        labelJumlah.setText("Jumlah");
        jPanel14.add(labelJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 250, 50));

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Jumlah");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, 20));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStatus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(51, 51, 51));
        labelStatus.setText("Status");
        jPanel15.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 250, 50));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Status");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 170, 20));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrioritas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelPrioritas.setForeground(new java.awt.Color(51, 51, 51));
        labelPrioritas.setText("Prioritas");
        jPanel16.add(labelPrioritas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 370, 50));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Prioritas");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 200, 20));

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Profil Sekolah");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatDokumenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDokumenBtnActionPerformed
        // Implementasi view dokumen pendukung
        try {
            List<Dokumen> dokumenList = dokumenService.getDokumenBySekolah(idSekolah);

            if (dokumenList.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Tidak ada dokumen pendukung untuk sekolah ini",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Ambil dokumen pertama dan buka
            Dokumen dok = dokumenList.get(0);
            String filePath = dok.getPathFile();

            if (filePath != null && !filePath.isEmpty()) {
                File file = new File(filePath);
                if (file.exists()) {
                    Desktop.getDesktop().open(file);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "File dokumen tidak ditemukan: " + filePath,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Path file tidak valid",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            logger.severe("Error opening dokumen: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error membuka dokumen: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lihatDokumenBtnActionPerformed

    private void verifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifBtnActionPerformed
        // Implementasi verifikasi sekolah
        try {
            kebutuhan.setStatus(Kebutuhan.Status.diverifikasi);
            kebutuhanDAO.update(kebutuhan);
            JOptionPane.showMessageDialog(this, "Kebutuhan berhasil diverifikasi!");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_verifBtnActionPerformed

    private void tolakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolakBtnActionPerformed
        // TODO add your handling code here:
         try {
            kebutuhan.setStatus(Kebutuhan.Status.ditolak);
            kebutuhanDAO.update(kebutuhan);
            JOptionPane.showMessageDialog(this, "Kebutuhan ditolak!");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tolakBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelAlamatSekolah;
    private javax.swing.JLabel labelDeskripsiKebutuhan;
    private javax.swing.JLabel labelJenisSekolah;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKabupaten;
    private javax.swing.JLabel labelKecamatan;
    private javax.swing.JLabel labelNPSN;
    private javax.swing.JLabel labelNamaAlat;
    private javax.swing.JLabel labelNamaFile;
    private javax.swing.JLabel labelNamaSekolah;
    private javax.swing.JLabel labelPrioritas;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JButton lihatDokumenBtn;
    private javax.swing.JButton tolakBtn;
    private javax.swing.JButton verifBtn;
    // End of variables declaration//GEN-END:variables
}
