package view.dialog;

import dao.KebutuhanDAO;
import dao.KebutuhanDAOImpl;
import model.Sekolah;
import model.Dokumen;
import service.SekolahService;
import service.DokumenService;
import java.util.Optional;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import model.Kebutuhan;

/**
 * DialogManajemenSekolah
 * Dialog untuk view detail informasi sekolah dan verifikasi
 * Terintegrasi penuh dengan Service Layer
 * 
 * @author aris
 */
public class DialogManajemenSekolah extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(DialogManajemenSekolah.class.getName());
    
    // Service Layer Integration
    private final SekolahService sekolahService;
    
    // Data Model
    // Data Model
    private Sekolah sekolahCurrent;
    private boolean isViewMode;
    private Integer idSekolah;


    /**
     * Constructor untuk view existing sekolah
     */
    public DialogManajemenSekolah(java.awt.Frame parent, boolean modal, Sekolah sekolah) {
     super(parent, modal);
     this.sekolahService = new SekolahService();
     this.sekolahCurrent = sekolah;
     this.isViewMode = true;

     // Ambil id dari objek sekolah
     this.idSekolah = sekolah != null ? sekolah.getIdSekolah() : null;

     initComponents();
     setupDialog();
     
     if (sekolahCurrent != null) {
            populateForm();
        } else {
            JOptionPane.showMessageDialog(this, "Data sekolah tidak valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            dispose();
        }
     }
     /**
     * Setup dialog properties
     */
    private void setupDialog() {
        setTitle("Detail Informasi Sekolah");
        setLocationRelativeTo(getParent());
        setResizable(false);
    }
    
    /**
     * Load data sekolah dari database
     */
    private void loadSekolahData() {
        if (idSekolah == null) {
            JOptionPane.showMessageDialog(this,
                "ID Sekolah tidak valid",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        
        try {
            Optional<Sekolah> sekolahOpt = sekolahService.getSekolahById(idSekolah);
            
            if (sekolahOpt.isPresent()) {
                this.sekolahCurrent = sekolahOpt.get();
                populateForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data sekolah tidak ditemukan",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                dispose();
            }
            
        } catch (Exception e) {
            logger.severe("Error loading sekolah data: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error loading data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
    
    /**
     * Populate form dengan data sekolah
     */
    private void populateForm() {
        if (sekolahCurrent == null) return;

        // Populate all fields
        labelNamaSekolah.setText(sekolahCurrent.getNamaSekolah());
        labelNPSN.setText(sekolahCurrent.getNpsn());
        labelJenisSekolah.setText(
            sekolahCurrent.getKategori() != null ? sekolahCurrent.getKategori().toString() : "-"
        );
        labelAlamatSekolah.setText(sekolahCurrent.getAlamatSekolah());
        labelKecamatan.setText(sekolahCurrent.getKecamatan());
        labelKabupaten.setText(sekolahCurrent.getKabupaten());
        labelStatusVerifikasi.setText("Status: " + sekolahCurrent.getStatusVerifikasi());

        String status = sekolahCurrent.getStatusVerifikasi() != null
                ? sekolahCurrent.getStatusVerifikasi().trim()
                : "";

        if (status.equalsIgnoreCase("Terverifikasi")) {
            jButton10.setVisible(false); // sembunyikan tombol
        } else {
            jButton10.setVisible(true);  // tampilkan tombol kalau belum
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelJenisSekolah = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelAlamatSekolah = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelNamaSekolah = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelNPSN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelKecamatan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelKabupaten = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        labelStatusVerifikasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Detail Sekolah");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJenisSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelJenisSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelJenisSekolah.setText("Jenis Sekolah");
        jPanel5.add(labelJenisSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAlamatSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelAlamatSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelAlamatSekolah.setText("Alamat Sekolah");
        jPanel4.add(labelAlamatSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNamaSekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNamaSekolah.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaSekolah.setText("Nama Sekolah");
        jPanel6.add(labelNamaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 50));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat Sekolah");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama Sekolah");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNPSN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelNPSN.setForeground(new java.awt.Color(51, 51, 51));
        labelNPSN.setText("NPSN");
        jPanel7.add(labelNPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 50));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("NPSN");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Jenis Sekolah");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKecamatan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelKecamatan.setForeground(new java.awt.Color(51, 51, 51));
        labelKecamatan.setText("Kecamatan");
        jPanel9.add(labelKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 50));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kecamatan");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKabupaten.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelKabupaten.setForeground(new java.awt.Color(51, 51, 51));
        labelKabupaten.setText("Kabupaten / Kota");
        jPanel10.add(labelKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 220, 50));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kabupaten / Kota");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 120, 20));

        jButton10.setBackground(new java.awt.Color(30, 136, 229));
        jButton10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Verifikasi");
        jButton10.setToolTipText("");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 130, 34));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Status Verifikasi");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStatusVerifikasi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelStatusVerifikasi.setForeground(new java.awt.Color(51, 51, 51));
        labelStatusVerifikasi.setText("Status Verifikasi");
        jPanel11.add(labelStatusVerifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, 40));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Implementasi verifikasi sekolah
        try {
            if (sekolahCurrent == null) {
                JOptionPane.showMessageDialog(this,
                        "Tidak ada data sekolah yang dipilih!",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int konfirmasi = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah Anda yakin ingin memverifikasi sekolah ini?",
                    "Konfirmasi Verifikasi",
                    JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                // Update status menjadi "Terverifikasi"
                sekolahCurrent.setStatusVerifikasi("Terverifikasi");
                boolean hasil = sekolahService.updateStatusVerifikasi(
                        sekolahCurrent.getIdSekolah(), "Terverifikasi");

                if (hasil) {
                    JOptionPane.showMessageDialog(this,
                            "Status sekolah berhasil diverifikasi!",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    dispose(); // tutup dialog
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal memperbarui status sekolah!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * Cleanup resources saat dialog ditutup
     */
    @Override
   public void dispose() {
       super.dispose();
   }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelAlamatSekolah;
    private javax.swing.JLabel labelJenisSekolah;
    private javax.swing.JLabel labelKabupaten;
    private javax.swing.JLabel labelKecamatan;
    private javax.swing.JLabel labelNPSN;
    private javax.swing.JLabel labelNamaSekolah;
    private javax.swing.JLabel labelStatusVerifikasi;
    // End of variables declaration//GEN-END:variables
}
