/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.Sekolah;
import service.SekolahService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import model.Kebutuhan;
import view.dialog.DialogManajemenSekolah;
import view.dialog.DialogTambahKebutuhan;
import view.dialog.DialogTambahSekolah;

/**
 * Panel untuk mengelola data sekolah
 * Menampilkan daftar sekolah dan menyediakan fungsi CRUD
 * 
 * @author ACER NITRO
 */
public class PanelSekolah extends javax.swing.JPanel {
    
    private final SekolahService sekolahService;
    private DefaultTableModel tableModel;
    private List<Sekolah> daftarSekolah;
    

    /**
     * Creates new form PanelSekolah
     */
    public PanelSekolah() {
        // Inisialisasi service
        this.sekolahService = new SekolahService();
        
        initComponents();
        
        // Setup setelah komponen diinisialisasi
        setupTable();
        loadDataSekolah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelSekolah = new javax.swing.JTable();
        lihatDetailBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Daftar sekolah yang mengajukan donasi");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tabelSekolah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelSekolah);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 630, 490));

        lihatDetailBtn.setBackground(new java.awt.Color(30, 136, 229));
        lihatDetailBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lihatDetailBtn.setForeground(new java.awt.Color(255, 255, 255));
        lihatDetailBtn.setText("Lihat Detail");
        lihatDetailBtn.setToolTipText("");
        lihatDetailBtn.setBorder(null);
        lihatDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDetailBtnActionPerformed(evt);
            }
        });
        jPanel8.add(lihatDetailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 130, 34));

        addBtn.setBackground(new java.awt.Color(0, 204, 51));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-add-20.png"))); // NOI18N
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel8.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 40, 30));

        refreshBtn.setBackground(new java.awt.Color(255, 255, 255));
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-refresh-20.png"))); // NOI18N
        refreshBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel8.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 40, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-trash-20.png"))); // NOI18N
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel8.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lihatDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelSekolah.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih sekolah terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // kalau suatu saat pakai sorter, aman-kan index:
        int modelRow = tabelSekolah.convertRowIndexToModel(selectedRow);
        Sekolah sekolahDipilih = daftarSekolah.get(modelRow);

        DialogManajemenSekolah dialog = new DialogManajemenSekolah(
                (java.awt.Frame) SwingUtilities.getWindowAncestor(this),
                true,
                sekolahDipilih
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // refresh setelah dialog ditutup
        loadDataSekolah();
    }//GEN-LAST:event_lihatDetailBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         DialogTambahSekolah dialog = new DialogTambahSekolah(
            (java.awt.Frame) SwingUtilities.getWindowAncestor(this), 
            true
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Setelah dialog ditutup, refresh tabel
        loadDataSekolah();
    }//GEN-LAST:event_addBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        loadDataSekolah();
        JOptionPane.showMessageDialog(this,
            "Data berhasil di-refresh!",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelSekolah.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Pilih sekolah yang ingin dihapus!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Ambil sekolah yang dipilih
        Sekolah sekolahTerpilih = daftarSekolah.get(selectedRow);
        
        // Konfirmasi hapus
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus sekolah:\n" + 
            sekolahTerpilih.getNamaSekolah() + "?\n\n" +
            "Perhatian: Sekolah yang memiliki data kebutuhan atau dokumen tidak bisa dihapus.",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
            
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                // Hapus sekolah menggunakan method yang benar dari SekolahService
                SekolahService.OperationResult result = 
                    sekolahService.deleteSekolah(sekolahTerpilih.getIdSekolah());
                
                if (result.isSuccess()) {
                    JOptionPane.showMessageDialog(this,
                        result.getMessage(),
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                        
                    // Refresh data
                    loadDataSekolah();
                } else {
                    JOptionPane.showMessageDialog(this,
                        result.getMessage(),
                        "Gagal",
                        JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error menghapus sekolah: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * Setup table dengan kolom yang sesuai
     */
    private void setupTable() {
        String[] columns = {
            "Nama Sekolah",
            "NPSN",
            "Jenis Sekolah",
            "Alamat",
            "Kecamatan",
            "Kabupaten",
            "Status Verifikasi"
        };

        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // semua kolom tidak bisa diedit
            }
        };

        tabelSekolah.setModel(tableModel);
        tabelSekolah.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelSekolah.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Atur lebar kolom biar rapi
        int[] widths = {180, 100, 90, 200, 130, 130, 130};
        for (int i = 0; i < widths.length; i++) {
            tabelSekolah.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }
    }


    
    /**
     * Load data sekolah dari database
     */
    private void loadDataSekolah() {
        try {
            tableModel.setRowCount(0);
            daftarSekolah = sekolahService.getAllSekolah();

            for (Sekolah sekolah : daftarSekolah) {
                Object[] row = {
                    sekolah.getNamaSekolah(),
                    sekolah.getNpsn(),
                    sekolah.getKategori() != null ? sekolah.getKategori().toString() : "-",
                    sekolah.getAlamatSekolah(),
                    sekolah.getKecamatan(),
                    sekolah.getKabupaten(),
                    sekolah.getStatusVerifikasi() != null ? sekolah.getStatusVerifikasi() : "-"
                };
                tableModel.addRow(row);
            }

            // Update label jumlah sekolah
            jLabel14.setText("Daftar Sekolah (" + daftarSekolah.size() + " sekolah terdaftar)");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error memuat data sekolah: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lihatDetailBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable tabelSekolah;
    // End of variables declaration//GEN-END:variables
}
