/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Kebutuhan;
import model.Pengguna;
import model.Sekolah;
import service.AuthenticationService;
import service.KebutuhanService;
import view.dialog.DialogDetailSekolah;

/**
 *
 * @author ACER NITRO
 */
public class PanelDaftarSekolah extends javax.swing.JPanel {

    private final KebutuhanService kebutuhanService;
    private DefaultTableModel modelKebutuhan;
    private final Pengguna user;
    /**
     * Creates new form PanelDaftarSekolah
     */
    public PanelDaftarSekolah(Pengguna user) {
        this.user = user;
        initComponents();
        kebutuhanService = new KebutuhanService();
        modelKebutuhan = (DefaultTableModel) tabelDaftarSekolah.getModel();

        styleTable(tabelDaftarSekolah);
        loadTabelKebutuhan();
    }
    
    private void styleTable(javax.swing.JTable table) {
        table.setFont(new java.awt.Font("Poppins", 0, 12));
        table.setRowHeight(28);
        table.setShowGrid(true);
        table.setGridColor(new java.awt.Color(220, 220, 220));
        table.setIntercellSpacing(new java.awt.Dimension(10, 5));
        table.getTableHeader().setReorderingAllowed(false);
        table.getTableHeader().setFont(new java.awt.Font("Poppins SemiBold", 0, 13));
        table.setSelectionBackground(new java.awt.Color(66, 135, 245));
        table.setSelectionForeground(java.awt.Color.WHITE);
        table.setFillsViewportHeight(true);

        // Center alignment untuk angka & tanggal
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        int columnCount = table.getColumnCount();
        for (int i = 0; i < columnCount; i++) {
            String name = table.getColumnName(i).toLowerCase();
            if (name.contains("jumlah") || name.contains("tanggal") || name.contains("prioritas")) {
                table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }
    }
    
    private void loadTabelKebutuhan() {
    // Header kolom tabel sekolah yang membutuhkan
        modelKebutuhan = new DefaultTableModel(
            new Object[]{"ID Kebutuhan", "Nama Sekolah", "Nama Alat", "Jumlah", "Keterangan"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tabelDaftarSekolah.setModel(modelKebutuhan);

        try {
            List<Kebutuhan> list = kebutuhanService.getKebutuhanTerverifikasi();

            for (Kebutuhan k : list) {
                String namaSekolah = (k.getSekolah() != null)
                        ? k.getSekolah().getNamaSekolah() : "-";
                String deskripsi = (k.getDeskripsi() != null && !k.getDeskripsi().isEmpty())
                        ? k.getDeskripsi() : "(Tanpa deskripsi)";
                String jumlah = (k.getJumlah() != null) ? k.getJumlah().toString() : "-";

                modelKebutuhan.addRow(new Object[]{
                    k.getIdKebutuhan(),
                    namaSekolah,
                    k.getNamaAlat(),
                    jumlah,
                    deskripsi
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal memuat data kebutuhan: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDaftarSekolah = new javax.swing.JTable();
        detailBtn = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Daftar Sekolah");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tabelDaftarSekolah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDaftarSekolah.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelDaftarSekolah);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 630, -1));

        detailBtn.setBackground(new java.awt.Color(30, 136, 229));
        detailBtn.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        detailBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailBtn.setText("Lihat Detail");
        detailBtn.setToolTipText("");
        detailBtn.setBorder(null);
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });
        jPanel8.add(detailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 130, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelDaftarSekolah.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih salah satu sekolah terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Integer idKebutuhan = Integer.parseInt(modelKebutuhan.getValueAt(selectedRow, 0).toString());
        KebutuhanService kebutuhanService = new KebutuhanService();

        kebutuhanService.getKebutuhanById(idKebutuhan).ifPresentOrElse(kebutuhan -> {
            Sekolah sekolah = kebutuhan.getSekolah();

            // Ambil user login dari AuthenticationService
            Pengguna user = AuthenticationService.getCurrentUser();

            // Pastikan kebutuhan != null dan sekolah != null
            if (kebutuhan == null || sekolah == null) {
                JOptionPane.showMessageDialog(this, "Data kebutuhan atau sekolah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DialogDetailSekolah dialog = new DialogDetailSekolah(
                    SwingUtilities.getWindowAncestor(this),
                    kebutuhan,
                    sekolah,
                    user
            );
            dialog.setVisible(true);

        }, () -> JOptionPane.showMessageDialog(this, "Data kebutuhan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE));
    }//GEN-LAST:event_detailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelDaftarSekolah;
    // End of variables declaration//GEN-END:variables
}
