/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import dao.KebutuhanDAO;
import dao.KebutuhanDAOImpl;
import java.util.List;
import java.util.Optional;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Kebutuhan;
import model.Sekolah;
import view.dialog.DialogTambahKebutuhan;

/**
 *
 * @author ACER NITRO
 */
public class PanelKebutuhan extends javax.swing.JPanel {

    /**
     * Creates new form PanelKebutuhan
     */
    private final Sekolah sekolahLogin;
    private final KebutuhanDAO kebutuhanDAO;
    private final DefaultTableModel tableModel;
    private List<Kebutuhan> daftarKebutuhan;

    public PanelKebutuhan(Sekolah sekolahLogin) {
        initComponents();
        this.sekolahLogin = sekolahLogin;
        this.kebutuhanDAO = new KebutuhanDAOImpl();

        // Model tabel
        tableModel = new DefaultTableModel(
            new Object[]{"ID", "Nama Kebutuhan", "Jumlah", "Status", "Prioritas", "Deskripsi"},
            0
        );
        tabelKebutuhan.setModel(tableModel);
        loadDataKebutuhan();

        // Styling tabel
        tabelKebutuhan.setRowHeight(28);
        tabelKebutuhan.setShowGrid(true);
        tabelKebutuhan.setGridColor(new java.awt.Color(220, 220, 220));
        tabelKebutuhan.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelKebutuhan.getTableHeader().setReorderingAllowed(false);
        tabelKebutuhan.getTableHeader().setFont(new java.awt.Font("Poppins SemiBold", 0, 13));
        tabelKebutuhan.setFont(new java.awt.Font("Poppins", 0, 12));

        // Lebar kolom proporsional
        int[] columnWidths = {40, 180, 80, 100, 100, 250};
        for (int i = 0; i < columnWidths.length; i++) {
            tabelKebutuhan.getColumnModel().getColumn(i).setPreferredWidth(columnWidths[i]);
        }

        // Center align untuk beberapa kolom
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabelKebutuhan.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tabelKebutuhan.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tabelKebutuhan.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tabelKebutuhan.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }


    private void loadDataKebutuhan() {
        try {
            if (sekolahLogin == null) {
                JOptionPane.showMessageDialog(this, "Data sekolah belum terdeteksi!");
                daftarKebutuhan = List.of(); // ✅ supaya gak null walau gagal
                return;
            }

            daftarKebutuhan = kebutuhanDAO.findByIdSekolah(sekolahLogin.getIdSekolah());
            tableModel.setRowCount(0);

            for (Kebutuhan k : daftarKebutuhan) {
                tableModel.addRow(new Object[]{
                    k.getIdKebutuhan(),
                    k.getNamaAlat(),
                    k.getJumlah() + " unit",
                    k.getStatus() != null ? k.getStatus().name() : "Belum Terpenuhi",
                    k.getPrioritas() != null ? k.getPrioritas().name() : "-",
                    k.getDeskripsi() == null ? "" : k.getDeskripsi()
                });
            }

        } catch (Exception e) {
            daftarKebutuhan = List.of(); // ✅ kalau error pun gak null
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKebutuhan = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        btnBuatKebutuhan = new javax.swing.JButton();
        editKebutuhanBtn = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Daftar Kebutuhan Sekolah");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tabelKebutuhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKebutuhan.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelKebutuhan);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 630, -1));

        jButton6.setBackground(new java.awt.Color(239, 68, 68));
        jButton6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Hapus Kebutuhan");
        jButton6.setToolTipText("");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 120, 34));

        btnBuatKebutuhan.setBackground(new java.awt.Color(30, 136, 229));
        btnBuatKebutuhan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnBuatKebutuhan.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatKebutuhan.setText("Buat Kebutuhan");
        btnBuatKebutuhan.setToolTipText("");
        btnBuatKebutuhan.setBorder(null);
        btnBuatKebutuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatKebutuhanActionPerformed(evt);
            }
        });
        jPanel8.add(btnBuatKebutuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 110, 34));

        editKebutuhanBtn.setBackground(new java.awt.Color(255, 204, 0));
        editKebutuhanBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        editKebutuhanBtn.setForeground(new java.awt.Color(255, 255, 255));
        editKebutuhanBtn.setText("Edit Kebutuhan");
        editKebutuhanBtn.setToolTipText("");
        editKebutuhanBtn.setBorder(null);
        editKebutuhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKebutuhanBtnActionPerformed(evt);
            }
        });
        jPanel8.add(editKebutuhanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 110, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelKebutuhan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih kebutuhan yang ingin dihapus!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (daftarKebutuhan == null || daftarKebutuhan.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Daftar kebutuhan belum dimuat!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        Kebutuhan kebutuhanTerpilih = daftarKebutuhan.get(selectedRow);

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus kebutuhan ini?\n"
                + "Nama: " + kebutuhanTerpilih.getNamaAlat(),
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                boolean berhasil = kebutuhanDAO.delete(kebutuhanTerpilih.getIdKebutuhan());
                if (berhasil) {
                    JOptionPane.showMessageDialog(this,
                            "Kebutuhan berhasil dihapus!",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    loadDataKebutuhan(); // refresh tabel
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal menghapus kebutuhan!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Terjadi kesalahan: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnBuatKebutuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatKebutuhanActionPerformed
        // TODO add your handling code here:
        java.awt.Window parent = SwingUtilities.getWindowAncestor(this);
        
        DialogTambahKebutuhan dialog = new DialogTambahKebutuhan((java.awt.Frame) parent, sekolahLogin);
        dialog.setVisible(true);
        loadDataKebutuhan();
    }//GEN-LAST:event_btnBuatKebutuhanActionPerformed

    private void editKebutuhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKebutuhanBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelKebutuhan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idKebutuhan = (int) tableModel.getValueAt(selectedRow, 0);

        try {
            Optional<Kebutuhan> opt = kebutuhanDAO.findById(idKebutuhan);
            if (opt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data kebutuhan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.awt.Window parent = SwingUtilities.getWindowAncestor(this);
            DialogTambahKebutuhan dialog = new DialogTambahKebutuhan((java.awt.Frame) parent, sekolahLogin, opt.get());
            dialog.setVisible(true);

            loadDataKebutuhan(); // refresh setelah edit
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_editKebutuhanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatKebutuhan;
    private javax.swing.JButton editKebutuhanBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKebutuhan;
    // End of variables declaration//GEN-END:variables
}
