/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import dao.KebutuhanDAO;
import dao.KebutuhanDAOImpl;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Kebutuhan;
import model.Sekolah;
import view.dialog.DialogDetailKebutuhan;

/**
 *
 * @author ACER NITRO
 */
public class PanelVerifikasiKebutuhan extends javax.swing.JPanel {

    /**
     * Creates new form PanelDokumen
     */
    private final KebutuhanDAO kebutuhanDAO;
    private DefaultTableModel tableModel;
    private List<Kebutuhan> daftarKebutuhan;

    public PanelVerifikasiKebutuhan() {
        initComponents();
        kebutuhanDAO = new KebutuhanDAOImpl();
        setupTable();
        loadDataKebutuhan();
    }

    
    private void setupTable() {
        tableModel = new DefaultTableModel(
                new Object[]{"ID", "Sekolah", "Nama Kebutuhan", "Jumlah", "Prioritas", "Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelVerif.setModel(tableModel);
        tabelVerif.setRowHeight(26);
        tabelVerif.getTableHeader().setReorderingAllowed(false);
    }

    private void loadDataKebutuhan() {
        try {
            daftarKebutuhan = kebutuhanDAO.findKebutuhanMenungguVerifikasi(); // ambil semua yg diajukan
            tableModel.setRowCount(0);

            for (Kebutuhan k : daftarKebutuhan) {
                Sekolah sekolah = k.getSekolah();
                String namaSekolah = sekolah != null ? sekolah.getNamaSekolah() : "-";

                tableModel.addRow(new Object[]{
                        k.getIdKebutuhan(),
                        namaSekolah,
                        k.getNamaAlat(),
                        k.getJumlah() + " unit",
                        k.getPrioritas() != null ? k.getPrioritas().name() : "-",
                        k.getStatus() != null ? k.getStatus().name() : "-"
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data kebutuhan: " + e.getMessage());
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelVerif = new javax.swing.JTable();
        lihatDetailBtn = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Kebutuhan yang perlu diperiksa");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tabelVerif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelVerif);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 640, -1));

        lihatDetailBtn.setBackground(new java.awt.Color(30, 136, 229));
        lihatDetailBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lihatDetailBtn.setForeground(new java.awt.Color(255, 255, 255));
        lihatDetailBtn.setText("Lihat Detail");
        lihatDetailBtn.setToolTipText("");
        lihatDetailBtn.setBorder(null);
        lihatDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDetailBtnActionPerformed(evt);
            }
        });
        jPanel8.add(lihatDetailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 130, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lihatDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelVerif.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih kebutuhan terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (daftarKebutuhan == null || daftarKebutuhan.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Data kebutuhan belum dimuat!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        Kebutuhan kebutuhanDipilih = daftarKebutuhan.get(selectedRow);
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);

        DialogDetailKebutuhan dialog = new DialogDetailKebutuhan(parentFrame, true, kebutuhanDipilih);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Refresh tabel setelah dialog ditutup
        loadDataKebutuhan();
    }//GEN-LAST:event_lihatDetailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihatDetailBtn;
    private javax.swing.JTable tabelVerif;
    // End of variables declaration//GEN-END:variables

}
