package view.dashboard;

import javax.swing.*;
import java.awt.*;
import model.Pengguna;
import service.AuthenticationService;
import view.auth.LoginForm;
import view.panel.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author ACER NITRO
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        if (AuthenticationService.getCurrentUser() == null) {
            JOptionPane.showMessageDialog(this, "Silakan login terlebih dahulu!");
            new LoginForm().setVisible(true);
            this.dispose();
            return;
        }

        
        initComponents();
        tampilkanInformasiPengguna();
        
        setMainPanel(new PanelDashboardAdmin());
        
    }
    
    private void setMainPanel(javax.swing.JPanel panel) {
            contentPanel.removeAll(); 
            contentPanel.setLayout(new java.awt.BorderLayout());
            contentPanel.add(panel, java.awt.BorderLayout.CENTER);
            contentPanel.revalidate();
            contentPanel.repaint();
        }
    
    
    
    private void tampilkanInformasiPengguna() {
        Pengguna user = AuthenticationService.getCurrentUser();
        
        if (user != null) {
            userLabel.setText(user.getNama());
            roleLabel.setText(user.getRole());
        } else {
            userLabel.setText("Tidak dikenal");
            roleLabel.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        msBtn = new javax.swing.JButton();
        mdntrBtn = new javax.swing.JButton();
        mdBtn = new javax.swing.JButton();
        mdkmnBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gambar/logo edushare.png"))); // NOI18N
        jLabel1.setText("EDUSHARE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 214, -1));

        dashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(51, 51, 51));
        dashboardBtn.setText(" Dashboard");
        dashboardBtn.setToolTipText("");
        dashboardBtn.setBorder(null);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel3.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 198, 34));

        msBtn.setBackground(new java.awt.Color(255, 255, 255));
        msBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        msBtn.setForeground(new java.awt.Color(51, 51, 51));
        msBtn.setText(" Manajemen Sekolah");
        msBtn.setToolTipText("");
        msBtn.setBorder(null);
        msBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msBtnActionPerformed(evt);
            }
        });
        jPanel3.add(msBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 198, 34));

        mdntrBtn.setBackground(new java.awt.Color(255, 255, 255));
        mdntrBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mdntrBtn.setForeground(new java.awt.Color(51, 51, 51));
        mdntrBtn.setText(" Manajemen Donatur");
        mdntrBtn.setToolTipText("");
        mdntrBtn.setBorder(null);
        mdntrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdntrBtnActionPerformed(evt);
            }
        });
        jPanel3.add(mdntrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 198, 34));

        mdBtn.setBackground(new java.awt.Color(255, 255, 255));
        mdBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mdBtn.setForeground(new java.awt.Color(51, 51, 51));
        mdBtn.setText(" Manajemen Donasi");
        mdBtn.setToolTipText("");
        mdBtn.setBorder(null);
        mdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdBtnActionPerformed(evt);
            }
        });
        jPanel3.add(mdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 198, 34));

        mdkmnBtn.setBackground(new java.awt.Color(255, 255, 255));
        mdkmnBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mdkmnBtn.setForeground(new java.awt.Color(51, 51, 51));
        mdkmnBtn.setText(" Manajemen Dokumen");
        mdkmnBtn.setToolTipText("");
        mdkmnBtn.setBorder(null);
        mdkmnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdkmnBtnActionPerformed(evt);
            }
        });
        jPanel3.add(mdkmnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 198, 34));

        logoutBtn.setBackground(new java.awt.Color(239, 68, 68));
        logoutBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 198, 34));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Selamat Datang, Admin!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 22, 235, 29));

        roleLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(51, 51, 51));
        roleLabel.setText("Role");
        jPanel2.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 29, -1, 30));

        userLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        userLabel.setForeground(new java.awt.Color(51, 51, 51));
        userLabel.setText("Nama akun");
        jPanel2.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMinimumSize(new java.awt.Dimension(900, 750));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 720, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Pengguna user = AuthenticationService.getCurrentUser();
        
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            AuthenticationService auth = new AuthenticationService();
            auth.logout();

            JOptionPane.showMessageDialog(this, "Logout berhasil. Sampai jumpa, " + user.getNama());
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void mdkmnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdkmnBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelVerifikasiKebutuhan());
    }//GEN-LAST:event_mdkmnBtnActionPerformed

    private void mdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDonasi());
    }//GEN-LAST:event_mdBtnActionPerformed

    private void mdntrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdntrBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDonatur());
    }//GEN-LAST:event_mdntrBtnActionPerformed

    private void msBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelSekolah());
    }//GEN-LAST:event_msBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDashboardAdmin());

    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton mdBtn;
    private javax.swing.JButton mdkmnBtn;
    private javax.swing.JButton mdntrBtn;
    private javax.swing.JButton msBtn;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
