package view.dashboard;

import view.auth.LoginForm;
import javax.swing.JOptionPane;
import model.Pengguna;
import service.AuthenticationService;
import view.panel.PanelDashboardDonatur;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author ACER NITRO
 */
public class DashboardDonatur extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardDonatur.class.getName());
    private final Pengguna user;
    
    /**
     * Creates new form DashboardDonatur
     */
    public DashboardDonatur(Pengguna user) {
        this.user = user;

        if (user == null) {
            JOptionPane.showMessageDialog(this, "Silakan login terlebih dahulu!");
            new LoginForm().setVisible(true);
            this.dispose();
            return;
        }

        initComponents();
        tampilkanInformasiPengguna();

        // Panel default saat pertama kali masuk dashboard
        setMainPanel(new PanelDashboardDonatur(user));

    }
    
    private void setMainPanel(javax.swing.JPanel panel) {
            contentPanel.removeAll(); // gunakan nama baru
            contentPanel.setLayout(new java.awt.BorderLayout());
            contentPanel.add(panel, java.awt.BorderLayout.CENTER);
            contentPanel.revalidate();
            contentPanel.repaint();
        }
    
    private void tampilkanInformasiPengguna() {
        Pengguna user = AuthenticationService.getCurrentUser();
        
        if (user != null) {
            userLabel.setText(user.getNama());
            roleLabel.setText(user.getRole());
            adminLabel.setText("Selamat Datang, " + user.getNama() + "!");
        } else {
            userLabel.setText("Tidak dikenal");
            roleLabel.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        daftarSekolahBtn = new javax.swing.JButton();
        riwayatDonasiBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        donasiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMinimumSize(new java.awt.Dimension(900, 750));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 720, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gambar/logo edushare.png"))); // NOI18N
        jLabel1.setText("EDUSHARE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 214, -1));

        dashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(51, 51, 51));
        dashboardBtn.setText(" Dashboard");
        dashboardBtn.setToolTipText("");
        dashboardBtn.setBorder(null);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel3.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 198, 34));

        daftarSekolahBtn.setBackground(new java.awt.Color(255, 255, 255));
        daftarSekolahBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        daftarSekolahBtn.setForeground(new java.awt.Color(51, 51, 51));
        daftarSekolahBtn.setText("Daftar Sekolah");
        daftarSekolahBtn.setToolTipText("");
        daftarSekolahBtn.setBorder(null);
        daftarSekolahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarSekolahBtnActionPerformed(evt);
            }
        });
        jPanel3.add(daftarSekolahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 198, 34));

        riwayatDonasiBtn.setBackground(new java.awt.Color(255, 255, 255));
        riwayatDonasiBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        riwayatDonasiBtn.setForeground(new java.awt.Color(51, 51, 51));
        riwayatDonasiBtn.setText("Riwayat Donasi");
        riwayatDonasiBtn.setToolTipText("");
        riwayatDonasiBtn.setBorder(null);
        riwayatDonasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatDonasiBtnActionPerformed(evt);
            }
        });
        jPanel3.add(riwayatDonasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 198, 34));

        logoutBtn.setBackground(new java.awt.Color(239, 68, 68));
        logoutBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 198, 34));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminLabel.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminLabel.setText("Selamat Datang, Dani!");
        jPanel2.add(adminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 22, 370, 29));

        roleLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(51, 51, 51));
        roleLabel.setText("Role");
        jPanel2.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 29, -1, 30));

        userLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        userLabel.setForeground(new java.awt.Color(51, 51, 51));
        userLabel.setText("Nama akun");
        jPanel2.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        donasiBtn.setBackground(new java.awt.Color(30, 136, 229));
        donasiBtn.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        donasiBtn.setForeground(new java.awt.Color(255, 255, 255));
        donasiBtn.setText("Donasi Sekarang");
        donasiBtn.setToolTipText("");
        donasiBtn.setBorder(null);
        donasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donasiBtnActionPerformed(evt);
            }
        });
        jPanel2.add(donasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 130, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donasiBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDaftarSekolah(user));
    }//GEN-LAST:event_donasiBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDashboardDonatur(user));
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void daftarSekolahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarSekolahBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDaftarSekolah(user));
    }//GEN-LAST:event_daftarSekolahBtnActionPerformed

    private void riwayatDonasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatDonasiBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelRiwayatDonasi());
    }//GEN-LAST:event_riwayatDonasiBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Pengguna user = AuthenticationService.getCurrentUser();
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            AuthenticationService auth = new AuthenticationService();
            auth.logout();

            JOptionPane.showMessageDialog(this, "Logout berhasil. Sampai jumpa, " + user.getNama());
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton daftarSekolahBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton donasiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton riwayatDonasiBtn;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
