package view.dashboard;

import view.auth.LoginForm;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Pengguna;
import model.PihakSekolah;
import model.Sekolah;
import service.AuthenticationService;
import view.dialog.DialogTambahKebutuhan;
import view.panel.PanelDashboardSekolah;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author ACER NITRO
 */
public class DashboardSekolah extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardSekolah.class.getName());
    private model.Sekolah sekolahLogin;

    /**
     * Creates new form DashboardSekolah
     */
    public DashboardSekolah() {
        if (AuthenticationService.getCurrentUser() == null) {
        JOptionPane.showMessageDialog(this, "Silakan login terlebih dahulu!");
        new LoginForm().setVisible(true);
        this.dispose();
        return;
        }

        initComponents();

        // === Ambil user login dan sekolah-nya ===
        var pengguna = AuthenticationService.getCurrentUser();
        if (pengguna instanceof model.PihakSekolah pihakSekolah) {
            sekolahLogin = pihakSekolah.getSekolah();
        }

        if (sekolahLogin == null) {
            JOptionPane.showMessageDialog(this, "Data sekolah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // === Default tampil panel dashboard utama ===
        setMainPanel(new PanelDashboardSekolah(sekolahLogin));
        tampilkanInformasiPihakSekolah();

    }
    
    private void setMainPanel(javax.swing.JPanel panel) {
            contentPanel.removeAll(); // gunakan nama baru
            contentPanel.setLayout(new java.awt.BorderLayout());
            contentPanel.add(panel, java.awt.BorderLayout.CENTER);
            contentPanel.revalidate();
            contentPanel.repaint();
        }
    
    private void tampilkanInformasiPihakSekolah() {
        // Ambil user yang sedang login dari AuthenticationService
        var pengguna = AuthenticationService.getCurrentUser();

        if (pengguna instanceof PihakSekolah) {
            PihakSekolah ps = (PihakSekolah) pengguna;
            Sekolah sekolah = ps.getSekolah();

            // Set teks label UI
            lblNamaSekolah.setText("Selamat Datang, " + sekolah.getNamaSekolah() + "!");
            lblNamaAkun.setText(ps.getNama()); // nama pribadi
            lblRole.setText(ps.getJabatan());  // jabatan sesuai database

            System.out.println("DEBUG >> Sekolah: " + sekolah.getNamaSekolah());
            System.out.println("DEBUG >> Jabatan: " + ps.getJabatan());
        } else {
            lblNamaSekolah.setText("Selamat Datang!");
            lblNamaAkun.setText("Tidak dikenal");
            lblRole.setText("-");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        manajemenKebutuhanBtn = new javax.swing.JButton();
        riwayatDonasiBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNamaSekolah = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblNamaAkun = new javax.swing.JLabel();
        tambahKebutuhanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMinimumSize(new java.awt.Dimension(900, 750));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 720, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gambar/logo edushare.png"))); // NOI18N
        jLabel1.setText("EDUSHARE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 214, -1));

        dashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(51, 51, 51));
        dashboardBtn.setText(" Dashboard");
        dashboardBtn.setToolTipText("");
        dashboardBtn.setBorder(null);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel3.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 198, 34));

        manajemenKebutuhanBtn.setBackground(new java.awt.Color(255, 255, 255));
        manajemenKebutuhanBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        manajemenKebutuhanBtn.setForeground(new java.awt.Color(51, 51, 51));
        manajemenKebutuhanBtn.setText("Manajemen Kebutuhan");
        manajemenKebutuhanBtn.setToolTipText("");
        manajemenKebutuhanBtn.setBorder(null);
        manajemenKebutuhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manajemenKebutuhanBtnActionPerformed(evt);
            }
        });
        jPanel3.add(manajemenKebutuhanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 198, 34));

        riwayatDonasiBtn.setBackground(new java.awt.Color(255, 255, 255));
        riwayatDonasiBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        riwayatDonasiBtn.setForeground(new java.awt.Color(51, 51, 51));
        riwayatDonasiBtn.setText("Riwayat Donasi");
        riwayatDonasiBtn.setToolTipText("");
        riwayatDonasiBtn.setBorder(null);
        riwayatDonasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatDonasiBtnActionPerformed(evt);
            }
        });
        jPanel3.add(riwayatDonasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 198, 34));

        logoutBtn.setBackground(new java.awt.Color(239, 68, 68));
        logoutBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 198, 34));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaSekolah.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblNamaSekolah.setForeground(new java.awt.Color(51, 51, 51));
        lblNamaSekolah.setText("Selamat Datang, SDN 004!");
        jPanel2.add(lblNamaSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 370, 29));

        lblRole.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(51, 51, 51));
        lblRole.setText("Role");
        jPanel2.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 100, 30));

        lblNamaAkun.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblNamaAkun.setForeground(new java.awt.Color(51, 51, 51));
        lblNamaAkun.setText("Nama akun");
        jPanel2.add(lblNamaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        tambahKebutuhanBtn.setBackground(new java.awt.Color(30, 136, 229));
        tambahKebutuhanBtn.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        tambahKebutuhanBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahKebutuhanBtn.setText("+ Tambah Kebutuhan");
        tambahKebutuhanBtn.setToolTipText("");
        tambahKebutuhanBtn.setBorder(null);
        tambahKebutuhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKebutuhanBtnActionPerformed(evt);
            }
        });
        jPanel2.add(tambahKebutuhanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 130, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelDashboardSekolah(sekolahLogin));
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void riwayatDonasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatDonasiBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelRiwayatDonasi());

    }//GEN-LAST:event_riwayatDonasiBtnActionPerformed

    private void tambahKebutuhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKebutuhanBtnActionPerformed
        // TODO add your handling code here:
        java.awt.Window parent = SwingUtilities.getWindowAncestor(this);
        
        DialogTambahKebutuhan dialog = new DialogTambahKebutuhan((java.awt.Frame) parent, sekolahLogin);
        dialog.setVisible(true);
    }//GEN-LAST:event_tambahKebutuhanBtnActionPerformed

    private void manajemenKebutuhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manajemenKebutuhanBtnActionPerformed
        // TODO add your handling code here:
        setMainPanel(new view.panel.PanelKebutuhan(sekolahLogin));
    }//GEN-LAST:event_manajemenKebutuhanBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
         Pengguna user = AuthenticationService.getCurrentUser();
        
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            AuthenticationService auth = new AuthenticationService();
            auth.logout();

            JOptionPane.showMessageDialog(this, "Logout berhasil. Sampai jumpa, " + user.getNama());
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardSekolah().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNamaAkun;
    private javax.swing.JLabel lblNamaSekolah;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manajemenKebutuhanBtn;
    private javax.swing.JButton riwayatDonasiBtn;
    private javax.swing.JButton tambahKebutuhanBtn;
    // End of variables declaration//GEN-END:variables
}
